########################################################################################################################
# Site Settings                                                                                                        #
########################################################################################################################
url: https://alsahfiza.github.io
baseurl: "https://alsahfiza.github.io"


########################################################################################################################
# General settings                                                                                                     #
########################################################################################################################

lang: en
title: Zakaria Alsahfi
description:     > 
                  Data Scientist<br>  
                  Data Analyst<br>  
                  Financial Data Analyst
# A shorter description for the sidebar.
tagline:         > 
                  Data Scientist<br>  
                  Data Analyst<br>  
                  Financial Data Analyst

keywords: [
  'zakaria',
  'zakaria alsahfi',
  'alsahfi',
  'alsahafi',
  'zakaria alsahafi',
  'portfolio',
  'Python',
  'R',
  'SQL',
  'NLP',
  'Tableau',
  'Power Bi',
  'Data Science',
  'Data Analysis',
  'Machine Learning',
  'Deep Learning',
  'Text Mining',
  'Data Visualization',
  'Data Mining',
  'TensorFlow',
  'Statistics',
  'Statstical Modeling',
  'Algorithm',
  'Recruitment Portfolio',
  'Professional Portfolio',
  'Candidate Portfolio',
  'Job Seeker Portfolio',
  'Hiring Portfolio',
  'Talent Showcase Portfolio',
  'Industry Expert Portfolio',
  'Professional Experience Portfolio',
  'Career Highlights Portfolio',
  'Skilled Professional Portfolio',
  'Portfolio for marketing job recruiters',
  'Tech job candidate online portfolio',
  'Best portfolio websites for finance professionals',
  'Graphic designer portfolio for creative headhunters',
  'Software developer work portfolio for tech recruiters'
  ]

# A (square) logo for the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo: /assets/img/logo.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  # Used by `jekyll-feed`:
  name: Zakaria Alsahfi
  email: zakaria.sahfi@gmail.com
  # # Used by `jekyll-seo-tag`:
  twitter: AlsahfiZA
  rss: true

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  googlescholar: true

# Add links to the sidebar.
menu:
  - title:             Blog
    url:               /posts/
  - title:           Power Bi
    url:              /powerbi/
  - title:            Tableau
    url:              /tableau/
  - title:             Resume
    url:               /resume/
  - title:             About Me
    url:               /about/

copyright:             © 2019. Zakaria Alsahfi. All rights reserved.

permalink:             /:categories/:year-:month-:day-:title/ #/projects/:title
# permalink:             none
########################################################################################################################
# Jekyll Customizations                                                                                                #
########################################################################################################################

# Sidebar image and theme color of the site.

accent_image:         /assets/img/bg-blue.jpg
# accent_image:
#   background:          /assets/img/background .webp
#   overlay:             false
accent_color:         rgb(0,174,239)

# This is used for the `theme-color` meta tag,
# which changes the background color of the browser UI in certain browsers.
# Defaults to `accent_color`.
#theme_color:         rgb(8,46,57)
theme_color:           rgb(31,55,75)

# The string encoding which fonts to fetch from Google Fonts.
# See: <https://hydejack.com/docs/configuration/>
google_fonts:        Roboto+Slab:700|Noto+Sans:400,400i,700,700i

# The text font. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font:               Noto Sans, Helvetica, Arial, sans-serif

# The font used for headings. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font_heading:       Roboto Slab, Helvetica, Arial, sans-serif

# The font used for code blocks. Expects a string that is a valid CSS font-family value.
font_code:           Fira Code, Menlo, Monaco, Consolas, monospace;

defaults:
  # You can use the following to enable comments on all posts.
  - scope:
      type:            posts
    values:
      # https://applause-button.com/
      applause_button:       true
  - scope:
      type:            powerbi
    values:
      # https://applause-button.com/
      applause_button:       true
  - scope:
      type:            tableau
    values:
      # https://applause-button.com/
      applause_button:       true 
      
  # Don't include documents in assets in the sitemap
  - scope:
      path:           assets/
    values:
      sitemap:         true

  # `jekyll-seo-tag` will mark collection outputs as `BlogPosting`,
  # but we want them to be `WebPage`s:
  - scope:
      type:           posts
    values:
      seo:
        type:         WebPage
  - scope:
      type:           powerbi
    values:
      seo:
        type:         WebPage
  - scope:
      type:           tableau
    values:
      seo:
        type:         WebPage
  # Don't include site verification file(for google) in the sitemap
  - scope:
      path:            google7a5b54f96ae6fbc3.html
    values:
      sitemap:         false

kramdown:
  math_engine:        katex
  math_engine_opts:   {}
  footnote_backlink:   "&#x21a9;&#xfe0e;"

########################################################################################################################
# Collections                                                                                                          #
########################################################################################################################

collections:
  featured_tags:
    permalink:         /tag/:name
    output:            true
  powerbi:
    permalink:         /powerbi/:path/
    output:            true
  projects:
    permalink:         /posts/:path/
    output:            true
  tableau:
    permalink:          /tableau/:path/
    output:             true
    

########################################################################################################################
# 3rd Party Integrations                                                                                               #
########################################################################################################################

# Set the Google Analytics id to receive `pageview` events.
# To remove Google Anaylics from the page, remove the line below.
google_analytics: G-MQVC3P7J7K

# Setting a disqus shortname will enable the comment section on
# pages with `comments: true` in the front matter.
# disqus: <username>

# Setting a tinyletter username will enable the newsletter subscription box.
# PRO version only!
tinyletter:           TsekNet

font-awesome:
  assets: true
  
lightbox:              true

mermaid:               true


########################################################################################################################
# Hydejack (website theme) settings                                                                                    #
########################################################################################################################

hydejack:
  # Configure the order of complementary content on blog posts
  post_addons:       [newsletter, about, related, random, comments]

  # Set to `true` if you don't want to show an icon indicating external links
  no_mark_external:   true

  # Set to `true` if third party plugins fail to work with dynamically loaded pages
  no_push_state:      false

  # Set to `true` if you want to disable the drawer
  no_drawer:         false

  # Set to `true` if you don't to use the auto-hiding (JavaScript based) navbar.
  # Note that this will not hide the navbar completely, only replace it with a static one.
  # Use custom css to hide completely, e.g. `#_navbar { display: none }`.
  no_navbar:         false

  # Set to true to disable the built-in search functionality.
  # Note that search is disabled during local use to save on build time.
  # Run Jekyll with the `JEKYLL_ENV` environment variable set to `production` to enable.
  no_search:         false

  # Set to `true` if you do not want parts of the css inlined in <head/>
  # This will increase site build speed dramatically!
  no_inline_css:     false

  # Set to `true` if you don't intend on changing the accent color on a per-page basis.
  # This will increase site build speed!
  no_page_style:     true

  # Code blocks and tables "break" the layout by spanning the full available width.
  # Set this to true if you want them to be the same width as other content.
  no_break_layout:   true

  # Set to `true` to disable the dynamic Table of Contents on large screens.
  no_toc:             false

  # When set to `true`, will not extend the content in the "third column" on large screens.
  # Instead, all content will remains within the center column.
  # Note that this will not affect the Table of Contents, use `no_toc` instead.
  no_third_column:   false

  # Set to `true` if you don't like oversized headlines on large screens.
  no_large_headings: true

  # You can set this to `true` if you don't want to set the `theme-color` meta tag,
  # This only affects the meta tag, not the color specified in the app manifest.
  no_theme_color:   false

  # Set to `true` when building with the `--lsi` option
  use_lsi:           true

  # When using Google Analytics, set to `true` to display a cookie notice banner.
  # When enabled, no user-related data will be stored until the user gives consent.
  cookies_banner:    true

  # Set to `true` if you would like to add a "Powered by Hydejack" link in the footer.
  # Note that this setting has no effect when using the free version.
  advertise:         false

  # Buyers of the PRO version can opt to hide all dates from the theme.
  # Frequent consumers of online content will know that nothing devalues a post like
  # seeing an old date.
  hide_dates:       false

  # Note that dark mode only works in the PRO version of Hydejack.
  dark_mode:
  # Set to `true` to always use the dark theme.
    always:         true
  # Set to `true` to use the dark theme based on visitors' preference (OS
  # setting).
    dynamic:        true
  # Set to `true` to allow visitors to switch between light and dark mode.
    icon:           false


# Separators
# ---------------------------------------------------------------------------------------
posted:                'Posted'
last_modified_at:      'Last modified at'
last_modified_at_icon: 'icon-history'
colon:                 ':'
separator:             '|'
category_start:        'in '
category_spearator:    ' / '
tag_start:             'on '
tag_separator:         ', '
from_to_separator:     '–'
breadcrumbs_home:      'home'
breadcrumbs_separator: '/'

# Date formats
# ---------------------------------------------------------------------------------------
date_formats:
  post:                '%d %b %Y'
  last_modified_at:    '%Y-%m-%d'
  related_post:        '%d %b %Y'
  list_group_by:       '%Y'
  list_entry:          '%d %b'
  project:             '%Y'
  projects_group_by:   '%Y'
  resume:              '%b %Y'
  
########################################################################################################################
# Only use if you know what Service Workers are and how they can impact the                                            #
# site!                                                                                                                #
########################################################################################################################

  offline:
    enabled:       false
    cache_version: 13
    precache_assets:
    - /assets/img/swipe.svg


########################################################################################################################
# File Inclusion/Exclusion                                                                                             #
########################################################################################################################

exclude:
  - .jekyll-cache
  - .sass-cache
  - '*.toml'
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
include:
  - .well-known
  - LICENSE.md


########################################################################################################################
# Plugins                                                                                                              #
########################################################################################################################

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jemoji

########################################################################################################################
# SEO                                                                                                                  #
########################################################################################################################

#  Where you proof that you own this site (used by jekyll-seo-tag)
#  google_analytics:    G-MQVC3P7J7K
google-site-verification: "ULEUQTgeP918_7Ne8oTWQBhH5P0Yp-HV5J9Y27p9uZI"
# -- or --
# webmaster_verifications:
# google:  ULEUQTgeP918_7Ne8oTWQBhH5P0Yp-HV5J9Y27p9uZI
# bing: <verification-id>
# alexa:<verification-id>
# yandex:  <verification-id>


# Used for twitter cards
twitter:
  username:  AlsahfiZA

# Used for facebook open graph
# facebook:
# app_id:  <id>
# publisher: <id>
# admins:  <id>

# Used on index and about sites
social:
  name: Zakaria Alsahfi
links:
- https://twitter.com/AlsahfiZA
- https://github.com/Zakaria-Alsahfi
- https://www.linkedin.com/in/zakariaalsahfi
- https://scholar.google.co.uk/citations?user=aJR6B78AAAAJ&hl=en

